### ISSUE TITLE
AWS Lambda support

### ISSUE THREAD

**Issue by ustroetz** [bugsnag/bugsnag-python#89]
Hi there - I am wondering if you have tried Bugsnag with AWS Lambda. We have so far little luck, since Lambda ends the session as soon as the function crashes. Would be awesome if you could add it to your Python integration guides.

We don't get it to work at all with unhandled errors.

We partly get it to work with handled errors. We log them:
```
from bugsnag.handlers import BugsnagHandler

logger = logging.getLogger('bugsnag.logger')
logger.addHandler(BugsnagHandler())
logger.warning('this is a warning')
```

The Cloudwatch logs for Lambda return the following:
```
START RequestId: e8de354c-71d7-419a-abfb-a2a109dd6435 Version: $LATEST 
2016-08-18 10:13:45 UTC
** [Bugsnag] Notification to https://notify.bugsnag.com failed
2016-08-18 10:13:45 UTC
Traceback (most recent call last): 
2016-08-18 10:13:45 UTC
 File "/var/task/bugsnag/notification.py", line 37, in request 
2016-08-18 10:13:45 UTC
 resp = urlopen(req) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen 
2016-08-18 10:13:45 UTC
 return opener.open(url, data, timeout) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 431, in open 
2016-08-18 10:13:45 UTC
 response = self._open(req, data) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 449, in _open 
2016-08-18 10:13:45 UTC
 '_open', req) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain 
2016-08-18 10:13:45 UTC
 result = func(*args) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open 
2016-08-18 10:13:45 UTC
 context=self._context) 
2016-08-18 10:13:45 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open 
2016-08-18 10:13:45 UTC
 raise URLError(err) 
2016-08-18 10:13:45 UTC
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
```
Thanks!

**Comment by kattrali** [comment]
Thank you for the detailed report, @ustroetz. I haven’t experimented with Lambda personally, but its something we can look into. 

> We have so far little luck, since Lambda ends the session as soon as the function crashes

There are a few things going on here. The crashing exception should be sent synchronously, as the process should be prevented from stopping before the report is sent. Setting the client config option `asynchronous` to false should fix this. However, you probably also want logged and handled errors to be sent asynchronously in general.

It looks like in the ideal case, you’d have two clients, one for handling uncaught errors, and other for the logger. The former would run with the config option `asynchronous` set to false. This is currently not possible, but something we are releasing in the near future. I’ve opened https://github.com/bugsnag/bugsnag-python/issues/93 to track this issue.

> The Cloudwatch logs for Lambda return the following:
```
START RequestId: e8de354c-71d7-419a-abfb-a2a109dd6435 Version: $LATEST 
2016-08-18 10:13:45 UTC
** [Bugsnag] Notification to https://notify.bugsnag.com failed
```

Hmm, looks like the notification gets stuck [here](https://github.com/bugsnag/bugsnag-python/blob/d2dea0358002d47e05d1d131a2edca5455187a9d/bugsnag/notification.py#L45), though this message is not logging the actual exception. I’ve opened https://github.com/bugsnag/bugsnag-python/issues/94 to fix this.

**Comment by ustroetz** [comment]
Thanks for having a look at this. 

We did try to sent the crashing exceptions synchronously by setting the config accordingly. However this also didn't prevent Lambda from stopping before the report is sent.

Regarding #94 we deployed Bugsnag `2.5.2` and have an eye on this issue.

**Comment by ustroetz** [comment]
After update to `2.5.2` we noticed the following logs for handled errors:

```
2016-08-25 09:07:38 UTC
** [Bugsnag] Notifying https://notify.bugsnag.com of exception 
2016-08-25 09:07:38 UTC
['password', 'password_confirmation', 'cookie', 'authorization']
```
```
** [Bugsnag] Notification to https://notify.bugsnag.com failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> 
2016-08-25 09:09:56 UTC
** [Bugsnag] Notification to https://notify.bugsnag.com failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> 
2016-08-25 09:09:56 UTC
Traceback (most recent call last): 
2016-08-25 09:09:56 UTC
 File "/var/task/bugsnag/notification.py", line 36, in request 
2016-08-25 09:09:56 UTC
 resp = urlopen(req) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen 
2016-08-25 09:09:56 UTC
 return opener.open(url, data, timeout) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 431, in open 
2016-08-25 09:09:56 UTC
 response = self._open(req, data) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 449, in _open 
2016-08-25 09:09:56 UTC
 '_open', req) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain 
2016-08-25 09:09:56 UTC
 result = func(*args) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open 
2016-08-25 09:09:56 UTC
 context=self._context) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open 
2016-08-25 09:09:56 UTC
 raise URLError(err) 
2016-08-25 09:09:56 UTC
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> 
2016-08-25 09:09:56 UTC
 Traceback (most recent call last): 
2016-08-25 09:09:56 UTC
 File "/var/task/bugsnag/notification.py", line 36, in request 
2016-08-25 09:09:56 UTC
 resp = urlopen(req) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen 
2016-08-25 09:09:56 UTC
 return opener.open(url, data, timeout) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 431, in open 
2016-08-25 09:09:56 UTC
 response = self._open(req, data) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 449, in _open 
2016-08-25 09:09:56 UTC
 '_open', req) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain 
2016-08-25 09:09:56 UTC
 result = func(*args) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open 
2016-08-25 09:09:56 UTC
 context=self._context) 
2016-08-25 09:09:56 UTC
 File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open 
2016-08-25 09:09:56 UTC
 raise URLError(err) 
2016-08-25 09:09:56 UTC
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)> 
2016-08-25 09:09:56 UTC
END RequestId: 370ae742-b5d7-4adb-b5d9-47df9254e76d
```

**Comment by kattrali** [comment]
Hmm, strange. Looks like a SSL cert problem on the host? That would be pretty strange though.

**Comment by kattrali** [comment]
Sorry about the delay. I went heads-down on a few issues to see if we can better handle the payload delivery and fix this issue properly. I just released a beta of [v3.0.0](https://github.com/bugsnag/bugsnag-python/blob/master/CHANGELOG.md#300b1-2016-09-13), which adds support for using requests (and therefore [its CA bundle or the certifi store](http://docs.python-requests.org/en/master/user/advanced/#ca-certificates)) when making secure requests. Requests delivery will be used by default if its available. Can you try a the [new beta](https://pypi.python.org/pypi/bugsnag/3.0.0b1) to see if it resolves your issue?

**Comment by ustroetz** [comment]
We deployed the new version and have an eye on it. We keep you posted. Thanks that you keep working on the issue.

**Comment by kattrali** [comment]
Hey, unless there is something new to report, I am going to close this out for now and revisit when investigating more specialized lambda integration. Feel free to reopen if anything related arises.

**Comment by IvanBernatovic** [comment]
I can't make this work for me. I'm using serverless framework with Python runtime and bugnsag `3.6.0` module and when I invoke lambda locally everything works as expected - logging ERROR types, reporting unhandled exceptions and reporting handled exceptions using `bugsnag.notify` method. However, when I deploy the same code to AWS it seems that reporting unhandled exceptions doesn't work.

In "normal" environment I know this isn't intended behaviour. I don't see AWS lambda mentioned anywhere in the docs so I guess it's not properly supported. But considering serverless services are becoming popular I would like for this to be looked into. 

The workaround for me was using a decorator for every lambda handler function, wrapping it in try-except block and "manually" reporting exceptions using `bugsnag.notify`. This is an example:
```python
def lambda_handler(lambda_function):
    @functools.wraps(lambda_function)
    def lambda_wrapper(*args, **kwargs):
        try:
            result = lambda_function(*args, **kwargs)
            return result
        except Exception as e:
            bugsnag.notify(e)

    return lambda_wrapper
```
It seems that your competitors such as Rollbar have the same issue so they [documented it and provided](https://docs.rollbar.com/docs/python#section-aws-lambda) a similar workaround.

**Comment by mattdyoung** [comment]
Hi @IvanBernatovic 

Can you confirm whether setting `asynchronous=False` allows delivery of your unhandled exceptions?
https://docs.bugsnag.com/platforms/python/other/configuration-options/#asynchronous

**Comment by IvanBernatovic** [comment]
Hi @mattdyoung,
I should have said that in my comment, but yes, I've set `asynchronous=False` and it changed nothing, the issue is still there.

**Comment by mattdyoung** [comment]
Hi @IvanBernatovic 

AWS Lambda isn't a platform we've officially tested and documented. It's something we have on our roadmap that we plan to officially add support for in the future, not just for Python but for Node.js, Java, C# etc as well.

That said, we have other customers who have reported getting this working successfully using Python simply by ensuring the VPC settings allow access to the internet and that reports are sent synchronously with `asynchronous=False`, so we believe it should be possible to get this to work.

**Comment by IvanBernatovic** [comment]
@mattdyoung I understand. I'm just reporting that the same code that locally works as expected (reports unhandled exceptions) is not working properly when deployed to Lambda service, not even with suggested additional options. That implies that I have a good configuration (works locally) so I'm confident it's Lambda related quirk. I'm glad that other customers don't have this issue but Lambda service has configuration options (specific runtime version, memory size, region) which may affect this. Thanks!

**Comment by princelySid** [comment]
Writing this because we took way too long to fix this ourselves. I think the problem is that by default bugsnag does things async and lamda shutdowns too quick. So set `asynchronous=False` in your configuration
```
bugsnag.configure(
        api_key=BUGSNAG_API_KEY,
        project_root="/var/task",
        asynchronous=False,
    )
```
